### ISSUE TITLE
Decoding non-json strings

### ISSUE THREAD

**Issue by danielenache** [chrismichaels84/eloquent-meta#17]
When storing a string that contains a string like "01.01.1970", the maybeDecode() function returns only the first two sequences, since json_decode() returns no error. The function should also check if the result of json_decode() is an object.

**Comment by chrismichaels84** [comment]
Well, I'm more than happy to make that adjustment, but I'm not sure the issue. Can you give me some code? When I try

```php
$json= '01.01.1970';
$actual = Helpers::maybeDecode($json);
$this->assertEquals('01.01.1970', $actual, 'failed to return almost json');
```

It returns the string, since it isn't json. Is that not what's expected?

I pushed a `HelpersTest` to the `master` branch.

**Comment by danielenache** [comment]
Perhaps it's also related to the PHP version. My results of the above test:
`
1) ActivityFieldTest::testHelper
failed to return almost json
Failed asserting that 1.01 matches expected '01.01.1970'.
`

This is with the current version of Helpers.php.
Changing the following:
```php
  public static function maybeDecode($value, $asArray = false)
    {

        if (!is_string($value)) {
            return $value;
        }

        $decoded = json_decode($value, $asArray);

        if (json_last_error() == JSON_ERROR_NONE && is_object($decoded)) {
            return $decoded;
        } else {
            // Reset the JSON error code:
            json_decode("[]");
            return $value;
        }
    }
```
results in passing the test correctly.

Running PHP 5.6.4 currently.

**Comment by chrismichaels84** [comment]
Well, that is weird. I am also using 5.6, but I think its 5.6.1. In any case, its a simple enough change. My only concern is if someone sets `asArray` to `true`, so it may be better to do a check for array or object.

**Comment by chrismichaels84** [comment]
I just pushed to `master` make sure that works.

**Comment by danielenache** [comment]
Looks fine.

Regards!
