### ISSUE TITLE
Issue in laravel 5.4

### ISSUE THREAD

**Issue by AvengersArmy** [chrismichaels84/eloquent-meta#21]
Following error displays on updatedMeta function.

Type error: Argument 1 passed to Illuminate\Validation\Factory::__construct() must implement interface Illuminate\Contracts\Translation\Translator, instance of Symfony\Component\Translation\Translator given, called in C:\xampp\htdocs\v2.superdash.ca\vendor\phoenix\eloquent-meta\src\Phoenix\EloquentMeta\Meta.php on line 77

Any advice towards resolution?

**Comment by AvengersArmy** [comment]
Any advice regarding the issue @chrismichaels84 ? If the package isn't supported, please do let me know!

**Comment by chrismichaels84** [comment]
Sorry about that, I've been away. I'm not sure how much I'm going to
 support this package. There never was much demand for the package, and I
haven't used Laravel in at least a year.

That said, I'm happy to look into this issue to see if its an easy fix.

**Comment by AvengersArmy** [comment]
Oh no worries, and I do use your package quite extensively actually and I sincerely do appreciate your efforts towards a fix for the issue. Let me know if you need any more details on the error.

**Comment by chrismichaels84** [comment]
Looking at it now. Should be a simple fix. I'm also going to do a new release specifically for Laravel 5.4 with some better tests.

**Comment by chrismichaels84** [comment]
@AvengersArmy Can you show me the code you were using when you produced this error?

**Comment by AvengersArmy** [comment]
@chrismichaels84 It was nothing too special, I was simply using your addMeta() & updateMeta() functions and it would display that error. When I looked into Laravel logs, that's when I realized that values were being passed through a validation instance in the package and causing the issue.

Eg.
$account->updateMeta('phone', $request->input('phone'));

Hopefully this helps.

**Comment by chrismichaels84** [comment]
Okay, well, I think I fixed this and all the tests pass. There *was* a bug, and good catch on your part. Still, I was never able to actually produce that bug. I don't know why. I'm going to release 1.6.1 now. Try that and see if it clears anything up :)

**Comment by AvengersArmy** [comment]
Perfect, I just updated via composer and the issue seems to be resolved. Thank you so much for your help!

**Comment by chrismichaels84** [comment]
:)
